name: quranic_journey
description: Aplikasi pembelajaran Al-Qur'an yang personal dengan gamifikasi dan AI
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.1.0
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  quran: ^1.4.1
  just_audio: ^0.10.5
  audio_service: ^0.18.11
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  google_generative_ai: ^0.4.7
  flutter_localizations:
    sdk: flutter
  marquee: ^2.3.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#006064"
  adaptive_icon_foreground: "assets/images/app_icon.png"
